### ISSUE TITLE
But how to use this tool? | 本插件如何配置使其工作？

### ISSUE THREAD

**Issue by geekyouth** [xylo/intellij-postfix-templates-generator#1]
i have read READ.MD carefully 

but i do not know how to use this tool 

![image](https://user-images.githubusercontent.com/12899262/70198781-cb0f0780-174a-11ea-831c-1514a2abf01d.png)

i am confused

**Comment by xylo** [comment]
Oh. I see. You can just change this directory to "templates" and it should work.
